import subprocess
from typing import Any, Protocol


class PlatformOps(Protocol):
    name: str  # "posix" | "nt"

    def configure_popen_group(self, popen_kwargs: dict[str, Any]) -> None: ...
    def pid_alive(self, pid: int) -> bool: ...
    def terminate_pid_tree(self, pid: int, *, force: bool) -> None: ...
    def terminate_process_tree(self, proc: subprocess.Popen[bytes], *, force: bool) -> None: ...
    def soft_terminate(self, proc: subprocess.Popen[bytes]) -> None: ...
    def hard_kill(self, proc: subprocess.Popen[bytes]) -> None: ...
