---
name: cpp_mandel (build + smoke)

defaults:
  run:
    working-directory: ./test_projects/cpp_mandel

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - "test_projects/cpp_mandel/**"

  pull_request:
    branches:
      - master
    paths:
      - "test_projects/cpp_mandel/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build-and-smoke:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show tool versions
        run: |
          ninja --version
          cmake --version

      - name: CMake Configure
        run: cmake --preset ci-release

      - name: CMake Build
        run: cmake --build --preset ci-release
